name: static-react-demo
static_sites:
  - environment_slug: html
    gitlab:
      branch: master
      deploy_on_push: true
      repo: CalMlynarczyk/digitalocean-static-react-demo
    name: static-react-demo
    build_command: npm run build
